apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdm-backend
  labels:
    app: pdm-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdm-backend
  template:
    metadata:
      labels:
        app: pdm-backend
    spec:
      containers:
        - name: pdm-backend
          image: docker-repo/predictive-maintenance-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
          # Optional: liveness/readiness probes to check the health of your container
          livenessProbe:
            httpGet:
              path: /status 
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pdm-backend-service
spec:
  selector:
    app: pdm-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
