version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: predictive_maintenance_backend
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: predictive_maintenance_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
